export const actions = {
  FETCH_WEATHER: 'FETCH_WEATHER',
  FETCH_WEATHER_FAIL:'FETCH_WEATHER_FAIL',
  FETCH_LETLONG:'FETCH_LETLONG',
  FETCH_LETLONG_FAIL:'FETCH_LETLONG_FAIL',
  START_LOADER:'START_LOADER',
  STOP_LOADER:'STOP_LOADER',



};

export default actions;
